version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    networks:
      - simple-kafka-programming-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.1
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - simple-kafka-programming-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_EXTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  topic-creator:
    build:
      context: ./topic-creator
    depends_on:
      - broker
    links:
      - broker:broker
    networks:
      - simple-kafka-programming-network
    environment:
      - hosts=broker:9092
  python-producer-1:
    build:
      context: ./python/producer
    depends_on:
      topic-creator:
        condition: service_completed_successfully
    links:
      - broker:broker
    networks:
      - simple-kafka-programming-network
    environment:
      - brokers=broker:9092
      - client-id=py-producer-1
      - topic=t.demo.topic.greeting
  python-producer-2:
    build:
      context: ./python/producer
    depends_on:
      topic-creator:
        condition: service_completed_successfully
    links:
      - broker:broker
    networks:
      - simple-kafka-programming-network
    environment:
      - brokers=broker:9092
      - client-id=py-producer-2
      - topic=t.demo.topic.greeting
  python-consumer:
    build:
      context: ./python/consumer
    depends_on:
      topic-creator:
        condition: service_completed_successfully
    links:
      - broker:broker
    networks:
      - simple-kafka-programming-network
    environment:
      - brokers=broker:9092
      - client-id=py-consumer
      - group-id=py-consumer-group
      - topic=t.demo.topic.greeting
    
networks:
  simple-kafka-programming-network:
    driver: bridge

